language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
cache: cargo
before_script: (cargo install cargo-travis && cargo install rustfmt)
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
after_success:
  - cargo coveralls
