[package]
name = "rulox"
version = "0.1.0"
authors = ["Mario Sangiorgio <mariosangiorgio@gmail.com>"]

[dependencies]
itertools = "0.5.9"
fnv = "1.0.6"
num-traits = "0.2"
num-derive = "0.2"

[dev-dependencies]
proptest = "0.7.0"

[profile.release]
debug = true
